receivers:
  otlp:
    protocols:
      grpc:
      http:
  kubeletstats:
    collection_interval: 30s # default is 10s
    metric_groups:
      - node
      - pod
exporters:
  debug:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": ${env:HONEYCOMB_API_KEY}
      "x-honeycomb-dataset": ${env:HONEYCOMB_DATASET}

processors:
  batch:
  metricstransform:
    transforms:
      - include: ^container\.(.*)$$
        match_type: regexp
        action: group
        group_resource_labels: {"resouce.type": "container", "source": "docker_stats"}
      - include: ^k8s\.pod\.(.*)$$
        match_type: regexp
        action: group
        group_resource_labels: {"resouce.type": "k8s.pod", "source": "kubelet"}
      - include: ^k8s\.node\.(.*)$$
        match_type: regexp
        action: group
        group_resource_labels: {"resouce.type": "k8s.node", "source": "kubelet"}
      - include: ^k8s\.container\.(.*)$$
        match_type: regexp
        action: group
        group_resource_labels: {"resouce.type": "k8s.container", "source": "kubelet"}
  attributes/metrics:
    actions:
      - key: device_major
        action: delete
        actions:
      - key: device_minor
        action: delete


extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]
    metrics:
      receivers: [otlp, kubeletstats]
      processors: [batch, metricstransform, attributes/metrics]
      exporters: [debug, otlp]