apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o kubernetes -c
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: otel-collector
  name: otel-collector
spec:
  ports:
    - name: "1888"
      port: 1888
      targetPort: 1888
    - name: "13133"
      port: 13133
      targetPort: 13133
    - name: "4317"
      port: 4317
      targetPort: 4317
    - name: "4318"
      port: 4318
      targetPort: 4318
    - name: "55679"
      port: 55679
      targetPort: 55679
  selector:
    io.kompose.service: otel-collector
status:
  loadBalancer: {}
